const actionTypes = {
  FORM: {
    RESET_STATE: 'FORM.RESET_STATE',
    SET_FIELD: 'FORM.SET_FIELD',
    SET_FIELD_VALIDATION_RESULT: 'FORM.SET_FIELD_VALIDATION_RESULT',
    SET_IS_VALIDATING: 'FORM.SET_IS_VALIDATING',
  },
  LOAD_DATA: {
    RESET_STATE: 'LOAD_DATA.RESET_STATE',
    REQUEST: 'LOAD_DATA.REQUEST',
    SUCCESS: 'LOAD_DATA.SUCCESS',
    FAILURE: 'LOAD_DATA.FAILURE',
  },
  UPDATE_DATA: {
    RESET_STATE: 'UPDATE_DATA.RESET_STATE',
    REQUEST: 'UPDATE_DATA.REQUEST',
    SUCCESS: 'UPDATE_DATA.SUCCESS',
    FAILURE: 'UPDATE_DATA.FAILURE',
  },
  CREATE_ACCOUNT: {
    RESET_STATE: 'CREATE_ACCOUNT.RESET_STATE',
  },
  LOGIN: {
    RESET_STATE: 'LOGIN.RESET_STATE',
  },
  FORGOT_PASSWORD: {
    RESET_STATE: 'FORGOT_PASSWORD.RESET_STATE',
  },
  TIME_MANAGEMENT: {
    RESET_STATE: 'TIME_MANAGEMENT.RESET_STATE',
    SET_DATA: 'TIME_MANAGEMENT.SET_DATA',
  },
  ADD_OR_EDIT_TIME_ZONE: {
    RESET_STATE: 'ADD_OR_EDIT_TIME_ZONE.RESET_STATE',
    SET_DATA: 'ADD_OR_EDIT_TIME_ZONE.SET_DATA',
  },
  USER_MANAGEMENT: {
    RESET_STATE: 'USER_MANAGEMENT.RESET_STATE',
    SET_DATA: 'USER_MANAGEMENT.SET_DATA',
  },
  ACCOUNT_INFO: {
    RESET_STATE: 'ACCOUNT_INFO.RESET_STATE',
    SET_DATA: 'ACCOUNT_INFO.SET_DATA',
  },
  ME: {
    RESET_STATE: 'ME.RESET_STATE',
    SET_DATA: 'ME.SET_DATA',
  },
};

const namespaces = Object.keys(actionTypes).reduce((acc, type) => ({ ...acc, [type]: type }), {});

export { actionTypes as default, namespaces };
